### ISSUE TITLE
Pitch code

### ISSUE THREAD

**Issue by ucasiggcas** [jmichel3/ms-thesis#3]
Dear,
Is there the source code of the [PDF](https://github.com/jmichel3/ms-thesis/blob/master/papers/pitch-detection/zolzerPLL.pdf) in language C/C++ or Python?
Have not found  the code,
Could you help me?
Please.

**Comment by jmichel3** [comment]
Hey @ucasiggcas, I'm not sure so I can't help unfortunately. At the time I wrote this thesis I also didn't have the source code for that paper. Good luck!
